name: Build & Publish auth service Docker Image

on:
    push:
        branches: 
            - main
        paths: 
            - 'User/**'
            
jobs:
    push_to_registry:
        name: Push Docker Image to Docker hub
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repo
              uses: actions/checkout@v3
            - name: Login to Docker Hub
              uses: docker/login-action@v2
              with:
                  username: ${{secrets.USERNAME}}
                  password: ${{secrets.PASSWORD}}
            - name: Build and Push Docker image
              uses: docker/build-push-action@v4
              with:
                  context: ./User
                  push: true
                  tags: aju404/e-commerce-user:latest
